# Generated by Django 6.1.1 on 2026-09-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Great Indian Festival', max_length=200)),
                ('subtitle', models.CharField(default='Powered by SAMSUNG Galaxy AI | Co-Powered by Intel CORE', max_length=300)),
                ('badge_text', models.CharField(default='Starts 8th Oct', max_length=100)),
                ('bank_offer_text', models.CharField(default='10% Instant Discount on Debit/Credit Cards & EMI', max_length=200)),
                ('bg_gradient', models.CharField(default='linear-gradient(90deg, #ff512f 0%, #dd2476 100%)', max_length=200)),
                ('image_url', models.URLField(blank=True, max_length=800)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
